FROM qt5.12-android:1.0

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/

# Set the QTDIR environment variable
ENV QTDIR /opt/Qt/5.12.6/android_armv7

# Add Android tools and platform tools to PATH
ENV ANDROID_HOME /opt/android/android-sdk

ENV ANDROID_SDK_ROOT /opt/android/android-sdk

ENV ANDROID_NDK_ROOT /opt/android/android-ndk
ENV ANDROID_NDK_HOST linux-x86_64

ENV PATH $ANDROID_HOME/tools/bin:$PATH
ENV PATH $ANDROID_HOME/platform-tools/bin:$PATH
ENV PATH $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

# Add further dependencies
RUN apt-get update && \
    apt-get install -y make autoconf m4 gcc-multilib

# Add ECL, C++17 capable version
RUN cd /root && \
    git clone https://gitlab.com/embeddable-common-lisp/ecl.git && \
    cd ecl && \
    git checkout 0cc0fd914a8a18f64e5f1ee5d29e9479d394be39 && \
    rm -rf .git/ && \
    cd /root && \
    mv ecl ecl-0cc0

# Add customized LQML
RUN cd /root && \
    git clone https://github.com/fbmnds/control-ui-lqml.git

# Prepare ECL directories for cross compilation
RUN cd /root && \
    mkdir -p .cache/common-lisp && \
    mkdir -p ecl/android/ecl-android && \
    mkdir -p ecl/android/ecl-android-host && \
    mkdir -p ecl/android/32bit/ecl-android && \
    mkdir -p ecl/android/32bit/ecl-android-host && \
    cp -r ecl-0cc0/* ecl/android/ && \
    cp -r ecl-0cc0/* ecl/android/32bit && \
    cd /root/control-ui-lqml/lqml/ && \
    cp platforms/android/build-ecl/*.sh /root/ecl/android && \
    cp platforms/android/build-ecl/32bit/*.sh /root/ecl/android/32bit/

# Compile host ECL
RUN cd /root/ecl-0cc0 &&\
    ./configure && \
    make && \
    make install && \
    rm -rf /root/ecl-0cc0

# Add Quicklisp
RUN cd /root && \
    curl -O https://beta.quicklisp.org/quicklisp.lisp && \
    ecl --load quicklisp.lisp --eval "(progn (quicklisp-quickstart:install) (quit))"

# Add cross-compiled ECL 64bit/32bit
ENV ANDROID_NDK_TOOLCHAIN $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
RUN cd /root/ecl/android && \
    ./1-make-ecl-host.sh && \
    ./2-make-ecl-android.sh && \
    cd 32bit && \
    ./1-make-ecl-host.sh && \
    ./2-make-ecl-android.sh

ENV ECL_ANDROID /root/ecl/android/ecl-android
ENV ECL_ANDROID_32 /root/ecl/android/32bit/ecl-android

COPY build.sh /build.sh

ENTRYPOINT /bin/bash /build.sh



## build an app in three steps
#export PROJECT_DIR /root/control-ui-lqml/lqml/apps/control-ui
#cd $PROJECT_DIR/build-android
#
## 1. qmake
#/opt/Qt/5.12.6/android_armv7/bin/qmake  "CONFIG+=32bit" ..
#
## 2. make
#make clean && \
#make install INSTALL_ROOT=$PROJECT_DIR/build-android/android-build/
#
## 3. androiddeployqt
#/opt/Qt/5.12.6/android_armv7/bin/androiddeployqt \
#  --input android-libapp.so-deployment-settings.json \
#  --output android-build --android-platform android-17 --jdk $JAVA_HOME --gradle
#
### works for QML apps without ECL
### TODO: make it work for LQML